import { useCallback, useEffect, useLayoutEffect, useRef, useState } from 'react';
import ReferenceRoomView, { REFERENCE_BINDINGS, REFERENCE_ICONS } from './ReferenceRoomView';
import { useWebRTC } from '../../hooks/useWebRTC';
import { useMeetingRecording } from '../../hooks/useMeetingRecording';
import { useStreamLevel } from '../../hooks/useStreamLevel';
import { useDialogFocus } from '../../hooks/useDialogFocus';
import { copyMeetingText } from '../../utils/meetingClipboard';
import { setAudioOutput } from '../../utils/meetingMedia';
import { getStoredUser } from '../../utils/auth';
import apiClient from '../../utils/apiClient';
import VideoCanvasProcessor from '../video/VideoCanvasProcessor';
import Whiteboard from '../features/Whiteboard';
import CaptionsOverlay from './CaptionsOverlay';
import { youtubeId, loadYouTubeApi } from '../../utils/youtube';
import { playMeetingSound } from '../../utils/meetingSounds';
import { avatarColor, nameTone as tone, tileShade } from '../../utils/avatarTone';
import { useTheme } from '../../utils/theme';
import { newId } from '../../utils/id';

const ini = name => (name || 'Guest').trim().split(/\s+/).filter(Boolean).slice(0,2).map(p=>p[0]).join('').toUpperCase();
const fmt = seconds => { const h=Math.floor(seconds/3600),m=String(Math.floor(seconds/60)%60).padStart(2,'0'),s=String(Math.max(0,seconds)%60).padStart(2,'0');return h?`${h}:${m}:${s}`:`${m}:${s}`; };
const TABS=['Audio','Video','Backgrounds','Notifications','Profile','Shortcuts','Appearance'];
const SHORTCUTS=[['M','Mute or unmute'],['V','Turn camera on or off'],['Hold Space','Talk while muted'],['Ctrl / ⌘ + E','Leave the meeting'],['H','Raise or lower hand'],['C','Open chat'],['Esc','Close menus and panels']];
const BGS=[['none','None','var(--c-15130f)'],['blur','Soft blur','radial-gradient(circle at 30% 30%, var(--c-3a3324), var(--c-12100d) 70%)'],['study','Study','linear-gradient(160deg, var(--c-2b2418), var(--c-0f0d0a))'],['studio','Studio','linear-gradient(180deg, var(--c-23262b), var(--c-0d0e10))'],['gold','Gold hour','radial-gradient(circle at 70% 20%, var(--c-5a4614), var(--c-14110a) 70%)']].map(([id,label,css])=>({id,label,css}));
const FILTERS=[['none','Natural','none'],['warm','Warm','sepia(.35) saturate(1.2)'],['mono','Mono','grayscale(1) contrast(1.1)'],['vivid','Vivid','saturate(1.6) contrast(1.05)'],['soft','Soft','brightness(1.08) contrast(.9)']].map(([id,label,css])=>({id,label,css}));
const IC=REFERENCE_ICONS;
const bgImage = bg => { if(/^data:image\/|^https?:\/\//i.test(bg||''))return bg;if(!bg||bg==='none'||bg==='blur')return 'none';const colors={study:['var(--c-2b2418)','var(--c-0f0d0a)'],studio:['var(--c-23262b)','var(--c-0d0e10)'],gold:['var(--c-5a4614)','var(--c-14110a)']},[a,b]=colors[bg]||colors.study;return 'data:image/svg+xml,'+encodeURIComponent(`<svg xmlns="http://www.w3.org/2000/svg" width="1280" height="720"><defs><linearGradient id="b" x2="1" y2="1"><stop stop-color="${a}"/><stop offset="1" stop-color="${b}"/></linearGradient></defs><path fill="url(#b)" d="M0 0h1280v720H0z"/></svg>`); };
function RemoteVoice({stream,output}){const ref=useRef(null);useEffect(()=>{if(ref.current&&stream){ref.current.srcObject=stream;ref.current.play().catch(()=>{});}},[stream]);useEffect(()=>{setAudioOutput(ref.current,output).catch(()=>{});},[output]);return <audio ref={ref} autoPlay/>;}

export default function ReferenceVideoRoom({roomCode,isHost,initialMedia,preferences,savePreferences}) {
  const [s,setS]=useState(()=>({panel:null,modal:null,menu:null,tab:'Audio',grid:true,spot:null,speaker:null,secs:0,fs:false,idle:false,ptt:false,left:false,ended:false,recAck:false,recStarted:null,
    name:initialMedia?.userName||getStoredUser()?.name||'Guest',q:'',openP:null,allStats:false,messages:[],draft:'',unread:false,previews:[],agendaPops:[],toasts:[],agendaDraft:'',pollQ:'',pollOpts:['',''],mediaKind:'video',mediaUrl:'',mediaErr:'',rating:0,fbText:'',fbSent:false,notes:'',inviteEmail:'',invited:[],copied:'',brCount:2,brMins:10,brSeed:0,breakout:null,roster:[],policy:{waitingRoom:true,allowChat:true,allowShare:true,allowDrawing:false},captionDemand:false,capLines:[],capNotice:'',stats:{},
    captions:false,bg:['blur','half-blur'].includes(preferences.filter)?'blur':BGS.some(b=>b.id===preferences.background)||/^data:image\/|^https?:\/\//i.test(preferences.background||'')?preferences.background:'none',filter:FILTERS.some(f=>f.id===preferences.filter)?preferences.filter:'none',selfHidden:false,lowBw:false,sounds:true,soundCues:true,chatNotif:true,handNotif:true,mirror:false,hd:true,showNames:true,rounded:true,...preferences.reference,mirror:!!initialMedia?.mirror}));
  const previousRoster=useRef(null);
  const stateRef=useRef(s);stateRef.current=s;
  const { resolved: resolvedTheme, setTheme }=useTheme();
  const [photoTones,setPhotoTones]=useState({});
  const patch=useCallback(updates=>setS(prev=>({...prev,...(typeof updates==='function'?updates(prev):updates)})),[]);
  const rootRef=useRef(null),dialogRef=useRef(null),previewRef=useRef(null),screenRef=useRef(null),rxRef=useRef(null),chatListRef=useRef(null),chatPinned=useRef(true),fileRef=useRef(null),mediaVideoRef=useRef(null),mediaAudioRef=useRef(null),youtubeRef=useRef(null),ytPlayerRef=useRef(null),focusRef=useRef(null),playbackRef=useRef(null);
  const toast=useCallback((text,who)=>{const id=newId();patch(prev=>({toasts:[...prev.toasts,{id,text,initials:ini(who||'EtherX')}].slice(-3)}));setTimeout(()=>patch(prev=>({toasts:prev.toasts.filter(t=>t.id!==id)})),4000);},[patch]);
  const rtc=useWebRTC(roomCode,{isHost,initialMedia,enabled:!s.left&&!s.ended,videoEffects:s.bg!=='none'||s.filter!=='none',onKicked:()=>patch({left:true}),onReplaced:()=>patch({left:true,replaced:true})});
  const rec=useMeetingRecording({roomCode,isHost:rtc.canHost,localStream:rtc.localStream,screenStream:rtc.screenStream,peers:rtc.peers,userName:s.name,socket:rtc.socket,socketReady:rtc.socketReady,onError:toast});
  const captionUpdate=useCallback(data=>patch({capLines:data.lines,capNotice:data.notice,capMissing:data.missing}),[patch]);
  const captionWarned=useRef(false);
  const captionUnavailable=useCallback(msg=>{if(captionWarned.current)return;captionWarned.current=true;toast(msg);},[toast]);
  const mutedLevel=useStreamLevel(s.left||s.ended?null:rtc.micMonitorStream,rtc.micMuted&&!rtc.hostMuted);
  const mutedTicks=useRef(0),hintTimer=useRef(null);
  useEffect(()=>{if(mutedLevel>.22)mutedTicks.current++;else mutedTicks.current=0;if(mutedTicks.current===6){patch({mutedHint:true});clearTimeout(hintTimer.current);hintTimer.current=setTimeout(()=>patch({mutedHint:false}),4000);}},[mutedLevel,patch]);
  useEffect(()=>()=>clearTimeout(hintTimer.current),[]);
  const [processed,setProcessed]=useState(null);
  const effects=s.bg!=='none'||s.filter!=='none';
  const processOutput=useCallback(stream=>{setProcessed(stream);rtc.setOutgoingVideoTrack(stream?.getVideoTracks()[0]||null);},[rtc.setOutgoingVideoTrack]);
  const emit=useCallback((event,data={})=>new Promise((resolve,reject)=>{if(!rtc.socket?.connected)return reject(new Error('Meeting disconnected. Try again.'));const timer=setTimeout(()=>reject(new Error('Server did not respond. Try again.')),8000);rtc.socket.emit(event,{roomCode,...data},reply=>{clearTimeout(timer);if(reply?.ok===false)reject(new Error(reply.error||'Action rejected.'));else resolve(reply);});}),[rtc.socket,roomCode]);
  const command=(event,data)=>emit(event,data).catch(e=>toast(e.message));
  const closeModal=useCallback(()=>{patch({modal:null});queueMicrotask(()=>focusRef.current?.isConnected?focusRef.current.focus():rootRef.current?.querySelector('[title="More options"]')?.focus());},[patch]);useDialogFocus(dialogRef,closeModal,!!s.modal);
  const openModal=(modal,extra={})=>{focusRef.current=document.activeElement.closest('footer [data-pop="menu"]')?rootRef.current?.querySelector('[title="More options"]'):document.activeElement;patch({modal,menu:null,...extra});};
  const menu=(kind)=>{focusRef.current=document.activeElement;patch(prev=>({menu:prev.menu===kind?null:kind}));};
  const openPanel=(kind)=>patch(prev=>({panel:prev.panel===kind?null:kind,menu:null,allStats:false,...(kind==='chat'?{unread:false,previews:[]}: {})}));
  const copy=async(value,key)=>{try{await copyMeetingText(value);patch({copied:key});setTimeout(()=>patch({copied:''}),2000);}catch(e){toast('Could not copy. Select the link and copy manually.');}};
  const link=window.location.origin+'/room/'+encodeURIComponent(roomCode);
  const leave=async(ended=false)=>{await rec.stopRecording();patch({left:!ended,ended,menu:null,modal:null,panel:null});sessionStorage.removeItem('etherx_host_room');};
  useEffect(()=>{if(s.left||s.ended)return;const timer=setInterval(()=>patch(prev=>({secs:prev.secs+1})),1000);return()=>clearInterval(timer);},[s.left,s.ended,patch]);
  useEffect(()=>{const resize=()=>patch({width:innerWidth,height:innerHeight});const fs=()=>patch({fs:!!document.fullscreenElement});window.addEventListener('resize',resize);document.addEventListener('fullscreenchange',fs);return()=>{window.removeEventListener('resize',resize);document.removeEventListener('fullscreenchange',fs);};},[patch]);
  const narrow=(s.width||innerWidth)<700;
  const onSpeaking=useCallback(key=>patch(prev=>prev.speaker===key?{}:{speaker:key}),[patch]);
  useEffect(()=>{if(!rtc.socket)return;const handlers={
    'meeting-policy':policy=>patch({policy}), 'roster-state':({members})=>patch({roster:members}), 'breakout-state':breakout=>{if(breakout&&!stateRef.current.breakout&&rtc.isScreenSharing)rtc.toggleScreenShare();patch({breakout});},
    'meeting-ended':()=>patch({ended:true,left:false,modal:null,panel:null,menu:null}), 'participant-renamed':({socketId,name})=>{if(socketId===rtc.mySocketId)patch({name});},
    'captions-demand':({active})=>patch({captionDemand:active}), 'recording-state':({state,startedAt})=>patch({recStarted:state==='recording'?startedAt:null,recAck:state!=='recording'||rtc.canHost}),
    'chat:message-created':message=>{if(message.roomCode!==roomCode)return;patch(prev=>({messages:prev.messages.some(m=>m._id===message._id)?prev.messages:[...prev.messages,message],unread:prev.panel!=='chat'&&String(message.senderId)!==String(getStoredUser()?.id),previews:prev.panel!=='chat'&&prev.chatNotif&&String(message.senderId)!==String(getStoredUser()?.id)?[...prev.previews,{id:message._id,who:message.address,text:message.message,initials:ini(message.address)}].slice(-2):prev.previews}));setTimeout(()=>patch(prev=>({previews:prev.previews.filter(p=>p.id!==message._id)})),6000);},
    'media-playback':data=>{playbackRef.current=data;if(ytPlayerRef.current?.getPlayerState)return applyYouTube(ytPlayerRef.current,data);const element=mediaVideoRef.current||mediaAudioRef.current;if(element&&element.readyState>0)applyPlayback(element,data);},
  };Object.entries(handlers).forEach(([event,handler])=>rtc.socket.on(event,handler));if(rtc.admitted&&rtc.socketReady)rtc.socket.emit('get-meeting-state',{roomCode});return()=>Object.entries(handlers).forEach(([event,handler])=>rtc.socket.off(event,handler));},[rtc.socket,rtc.mySocketId,rtc.admitted,rtc.socketReady,rtc.canHost,roomCode,patch,toast]);
  // Followers keep the sharer's YouTube position (within 1.5 s) and play/pause state.
  function applyYouTube(player,data){const time=data.time+(data.paused?0:(Date.now()-data.sentAt)/1000);if(Math.abs((player.getCurrentTime?.()||0)-time)>1.5)player.seekTo(time,true);if(data.paused)player.pauseVideo();else player.playVideo();}
  function applyPlayback(element,data){const time=data.time+(data.paused?0:(Date.now()-data.sentAt)/1000);if(Math.abs(element.currentTime-time)>.5)element.currentTime=time;if(data.paused)element.pause();else element.play().catch(()=>{});}
  useEffect(()=>{if(rtc.screenShareNotice)toast(rtc.screenShareNotice);},[rtc.screenShareNotice,toast]);
  useEffect(()=>{if(rtc.mediaError)toast(rtc.mediaError);},[rtc.mediaError,toast]);
  const joinedReady=rtc.admitted&&s.roster.some(p=>p.socketId===rtc.mySocketId);
  useEffect(()=>{if(!joinedReady||s.left||s.ended)return;let alive=true;const load=async()=>{try{const res=await apiClient.get(`/api/rooms/chat/${roomCode}`);if(alive)patch({messages:res.data?.data||[]});}catch(e){toast('Chat could not load. Open chat to retry.');}};load();const timer=setInterval(load,10000);return()=>{alive=false;clearInterval(timer);};},[joinedReady,roomCode,s.left,s.ended,patch,toast]);
  // Chat follows new messages while the reader is at the bottom (and always for their own); scrolling up to read older ones stops it.
  useEffect(()=>{const el=chatListRef.current;if(!el)return;const onScroll=()=>{chatPinned.current=el.scrollHeight-el.scrollTop-el.clientHeight<80;};el.addEventListener('scroll',onScroll);return()=>el.removeEventListener('scroll',onScroll);},[s.panel]);
  useEffect(()=>{const el=chatListRef.current;if(!el)return;const last=s.messages.at(-1);if(chatPinned.current||String(last?.senderId)===String(getStoredUser()?.id))el.scrollTop=el.scrollHeight;},[s.messages]);
  useEffect(()=>{const el=chatListRef.current;if(el){el.scrollTop=el.scrollHeight;chatPinned.current=true;}},[s.panel]);
  useEffect(()=>{if(previewRef.current&&rtc.localStream){previewRef.current.srcObject=effects&&processed?processed:rtc.localStream;previewRef.current.play().catch(()=>{});}},[rtc.localStream,s.modal,s.tab,effects,processed]);
  useEffect(()=>{if(screenRef.current&&rtc.screenStream){screenRef.current.srcObject=rtc.screenStream;screenRef.current.play().catch(()=>{});}},[rtc.screenStream,rtc.isScreenSharing]);
  useEffect(()=>{const element=mediaVideoRef.current||mediaAudioRef.current;if(!element)return;
    // The view renders empty media elements: load the shared file into whichever one is showing.
    if(rtc.sharedMediaUrl&&element.getAttribute('src')!==rtc.sharedMediaUrl){element.src=rtc.sharedMediaUrl;element.play?.().catch(()=>{});}
    const send=()=>{if(rtc.canHost)rtc.socket?.emit('media-playback',{roomCode,time:element.currentTime,paused:element.paused});};const ready=()=>{if(!rtc.canHost&&playbackRef.current)applyPlayback(element,playbackRef.current);};const error=()=>toast('Shared media could not load. Check that the link points to a playable audio or video file.');['play','pause','seeked'].forEach(event=>element.addEventListener(event,send));element.addEventListener('loadedmetadata',ready);element.addEventListener('error',error);const timer=setInterval(send,2000);setAudioOutput(element,preferences.outputDevice).catch(()=>{});return()=>{clearInterval(timer);['play','pause','seeked'].forEach(event=>element.removeEventListener(event,send));element.removeEventListener('loadedmetadata',ready);element.removeEventListener('error',error);};},[rtc.sharedMediaUrl,rtc.sharedMediaKind,rtc.canHost,rtc.socket,roomCode,preferences.outputDevice,toast]);

  // Shared YouTube video: YouTube's own player in the media tile. The sharer (host/co-host) drives it;
  // play, pause and seek go out over the same media-playback sync as video files.
  const canHostRef=useRef(rtc.canHost);canHostRef.current=rtc.canHost;
  useEffect(()=>{const id=rtc.sharedMediaKind==='youtube'?youtubeId(rtc.sharedMediaUrl):null;const host=youtubeRef.current;if(!id||!host)return undefined;
    let player=null,timer=null,cancelled=false;const mount=document.createElement('div');host.replaceChildren(mount);
    const send=()=>{if(canHostRef.current&&player?.getPlayerState)rtc.socket?.emit('media-playback',{roomCode,time:player.getCurrentTime()||0,paused:player.getPlayerState()!==1});};
    loadYouTubeApi().then(YT=>{if(cancelled)return;player=new YT.Player(mount,{videoId:id,width:'100%',height:'100%',playerVars:{autoplay:1,playsinline:1,rel:0,modestbranding:1},
      events:{onReady:e=>{ytPlayerRef.current=e.target;if(!canHostRef.current&&playbackRef.current)applyYouTube(e.target,playbackRef.current);else e.target.playVideo();},
        onStateChange:e=>{if(e.data===1||e.data===2)send();},
        onError:()=>toast('This YouTube video cannot be played here (it may block embedding or be private).')}});
      timer=setInterval(send,2000);}).catch(()=>toast('YouTube could not be loaded. Check your connection.'));
    return()=>{cancelled=true;clearInterval(timer);ytPlayerRef.current=null;try{player?.destroy();}catch{/* already gone */}host.replaceChildren();};
  },[rtc.sharedMediaUrl,rtc.sharedMediaKind,rtc.socket,roomCode,toast]);

  // Controls fade after 3s idle. On touch screens the tap that brings them back only reveals them,
  // like Meet: it must not also pin a tile or press a control the user could not see.
  useEffect(()=>{let timer,revealTap=false,revealTimer;const move=event=>{if(event?.type==='pointerdown'&&event.pointerType!=='mouse'&&stateRef.current.idle&&!stateRef.current.menu&&!stateRef.current.panel&&!stateRef.current.modal){revealTap=true;clearTimeout(revealTimer);revealTimer=setTimeout(()=>{revealTap=false;},600);}patch(prev=>prev.idle?{idle:false}:{});clearTimeout(timer);timer=setTimeout(()=>patch({idle:true}),3000);};const swallow=event=>{if(!revealTap)return;revealTap=false;event.preventDefault();event.stopPropagation();};['pointermove','pointerdown','keydown'].forEach(event=>window.addEventListener(event,move));window.addEventListener('click',swallow,true);move();return()=>{clearTimeout(timer);clearTimeout(revealTimer);['pointermove','pointerdown','keydown'].forEach(event=>window.removeEventListener(event,move));window.removeEventListener('click',swallow,true);};},[patch]);
  useEffect(()=>{if(!s.menu)return;const outside=event=>{if(!event.target.closest('[data-pop="menu"]')&&!event.target.closest('footer button'))patch({menu:null});};document.addEventListener('pointerdown',outside);return()=>document.removeEventListener('pointerdown',outside);},[s.menu,patch]);
  useEffect(()=>{if(!s.menu)return;const pop=rootRef.current?.querySelector('footer [data-pop="menu"]');const buttons=[...(pop?.querySelectorAll('button:not(:disabled)')||[])];buttons[0]?.focus();const navigate=e=>{if(!['ArrowDown','ArrowUp','Home','End','Escape'].includes(e.key))return;e.preventDefault();e.stopImmediatePropagation();if(e.key==='Escape'){patch({menu:null});focusRef.current?.focus?.();return;}const index=buttons.indexOf(document.activeElement),next=e.key==='Home'?0:e.key==='End'?buttons.length-1:(index+(e.key==='ArrowUp'?-1:1)+buttons.length)%buttons.length;buttons[next]?.focus();};document.addEventListener('keydown',navigate,true);return()=>document.removeEventListener('keydown',navigate,true);},[s.menu,patch]);
  useEffect(()=>{const keydown=event=>{if(event.target.closest('input,textarea,select,[contenteditable="true"]')||s.modal||s.left||s.ended||event.repeat)return;const key=event.key.toLowerCase();if((event.ctrlKey||event.metaKey)&&key==='e'){event.preventDefault();rtc.canHost?menu('leave'):leave();return;}if(event.ctrlKey||event.metaKey||event.altKey)return;if(key==='escape'){patch({menu:null,panel:null,modal:null});focusRef.current?.focus?.();return;}if(key==='m'){event.preventDefault();rtc.toggleMic();}if(key==='v'){event.preventDefault();rtc.toggleCamera();}if(key==='h'){event.preventDefault();rtc.handQueue.some(h=>h.socketId===rtc.mySocketId)?rtc.sendHandLower():rtc.sendHandRaise();}if(key==='c'){event.preventDefault();openPanel('chat');}if(event.code==='Space'&&rtc.micMuted&&!rtc.hostMuted&&event.target===document.body){event.preventDefault();patch({ptt:true});rtc.toggleMic();}};const up=event=>{if(event.code==='Space'&&stateRef.current.ptt){patch({ptt:false});rtc.toggleMic();}};document.addEventListener('keydown',keydown);document.addEventListener('keyup',up);const blur=()=>{if(stateRef.current.ptt){patch({ptt:false});rtc.toggleMic();}};window.addEventListener('blur',blur);return()=>{document.removeEventListener('keydown',keydown);document.removeEventListener('keyup',up);window.removeEventListener('blur',blur);};},[s.modal,s.left,s.ended,rtc.micMuted,rtc.hostMuted,rtc.canHost,rtc.mySocketId,rtc.handQueue,rtc.toggleMic,rtc.toggleCamera,patch]);
  useEffect(()=>{let alive=true;const previous={};const poll=async()=>{const stats={};for(const [id,pc] of Object.entries(rtc.peerConnections.current)){try{const report=await pc.getStats();let width,height,fps,bytes=0,packets=0,lost=0,rtt;report.forEach(row=>{if(row.type==='inbound-rtp'){bytes+=row.bytesReceived||0;packets+=row.packetsReceived||0;lost+=Math.max(0,row.packetsLost||0);if(row.kind==='video'||row.mediaType==='video'){width=row.frameWidth;height=row.frameHeight;fps=row.framesPerSecond;}}if(row.type==='candidate-pair'&&row.state==='succeeded')rtt=row.currentRoundTripTime;});const now=performance.now(),old=previous[id];stats[id]=[['Resolution',width?`${width}×${height}`:'Audio only'],['Frame rate',fps?`${Math.round(fps)} fps`:'—'],['Bitrate',old?`${Math.max(0,Math.round((bytes-old.bytes)*8/(now-old.at)))} kbps`:'Measuring…'],['Packet loss',packets+lost?`${(lost/(packets+lost)*100).toFixed(1)}%`:'0%'],['Latency',Number.isFinite(rtt)?`${Math.round(rtt*1000)} ms`:'Measuring…']].map(([l,v])=>({l,v}));previous[id]={bytes,at:now};}catch{}}if(alive)patch({stats});};poll();const timer=setInterval(poll,2000);return()=>{alive=false;clearInterval(timer);};},[rtc.peerConnections,patch]);
  useEffect(()=>{if(!joinedReady)return;const current=new Map(s.roster.map(p=>[p.socketId,p]));const previous=previousRoster.current;if(previous&&s.sounds){for(const [id,p] of current)if(!previous.has(id))toast(p.userName+' joined',p.userName);for(const [id,p] of previous)if(!current.has(id))toast(p.userName+' left',p.userName);}if(previous&&s.soundCues){const joined=[...current.keys()].some(id=>!previous.has(id)),left=[...previous.keys()].some(id=>!current.has(id));if(joined)playMeetingSound('join');else if(left)playMeetingSound('leave');}previousRoster.current=current;},[s.roster,joinedReady,s.sounds,s.soundCues,toast]);
  const previousHands=useRef(new Set());
  useEffect(()=>{const current=new Set(rtc.handQueue.map(h=>h.socketId));if(s.handNotif)rtc.handQueue.forEach(h=>{if(!previousHands.current.has(h.socketId)&&h.socketId!==rtc.mySocketId)toast(h.userName+' raised their hand',h.userName);});if(s.soundCues&&rtc.handQueue.some(h=>!previousHands.current.has(h.socketId)&&h.socketId!==rtc.mySocketId))playMeetingSound('hand');previousHands.current=current;},[rtc.handQueue,rtc.mySocketId,s.handNotif,s.soundCues,toast]);
  // Chimes for popups (chat, polls, files, agenda), join requests and someone else starting a screen share. First values seed the baseline.
  const previousPops=useRef(null),previousKnocks=useRef(0),previousSharer=useRef(undefined);
  useEffect(()=>{const ids=new Set([...s.previews.map(p=>p.id),...rtc.pollNotifications.map(p=>'poll-'+p.id),...rtc.fileNotifications.filter(f=>f.sharedBySocketId!==rtc.mySocketId).map(f=>'file-'+f.id),...s.agendaPops.map(p=>p.id)]);const previous=previousPops.current;previousPops.current=ids;if(previous&&stateRef.current.soundCues&&[...ids].some(id=>!previous.has(id)))playMeetingSound('message');},[s.previews,s.agendaPops,rtc.pollNotifications,rtc.fileNotifications,rtc.mySocketId]);
  useEffect(()=>{const count=rtc.joinRequests.length;if(count>previousKnocks.current&&stateRef.current.soundCues)playMeetingSound('knock');previousKnocks.current=count;},[rtc.joinRequests]);
  useEffect(()=>{const id=rtc.screenSharerId||null;if(previousSharer.current!==undefined&&id&&id!==previousSharer.current&&id!==rtc.mySocketId&&stateRef.current.soundCues)playMeetingSound('share');previousSharer.current=id;},[rtc.screenSharerId,rtc.mySocketId]);
  // Agenda popups, like chat previews: a topic added or covered by someone else. The first agenda load seeds the baseline.
  const previousAgenda=useRef(null);
  useEffect(()=>{if(!rtc.agendaReady)return;const previous=previousAgenda.current;previousAgenda.current=new Map(rtc.agendaItems.map(a=>[a.id,a.done]));if(!previous)return;const pops=[];for(const a of rtc.agendaItems){if(!previous.has(a.id)&&a.createdById!==rtc.mySocketId)pops.push({id:'agenda-add-'+a.id,who:a.createdBy+' added to the agenda',text:a.title,initials:ini(a.createdBy)});else if(previous.has(a.id)&&a.done&&!previous.get(a.id)&&a.toggledById!==rtc.mySocketId)pops.push({id:'agenda-done-'+a.id+'-'+Date.now(),who:a.toggledBy+' covered a topic',text:a.title,initials:ini(a.toggledBy)});}if(!pops.length)return;patch(prev=>({agendaPops:[...prev.agendaPops,...pops].slice(-3)}));pops.forEach(pop=>setTimeout(()=>patch(prev=>({agendaPops:prev.agendaPops.filter(p=>p.id!==pop.id)})),6000));},[rtc.agendaItems,rtc.agendaReady,rtc.mySocketId,patch]);
  useEffect(()=>{if(!joinedReady||!s.name.trim())return;const timer=setTimeout(()=>{const name=s.name.trim().slice(0,80);rtc.updateDisplayName(name);emit('rename-participant',{name}).catch(e=>toast(e.message));},500);return()=>clearTimeout(timer);},[s.name,joinedReady,emit,toast]);
  useEffect(()=>{const track=rtc.localStream?.getVideoTracks()[0];if(track?.readyState==='live')track.applyConstraints({width:{ideal:s.hd?1280:640},height:{ideal:s.hd?720:360},frameRate:{ideal:s.hd?30:15}}).catch(()=>toast('Camera cannot use that video quality.'));},[s.hd,rtc.localStream,toast]);
  useEffect(()=>{if(joinedReady)emit('request-media-quality',{low:s.lowBw}).catch(e=>toast(e.message));},[s.lowBw,joinedReady,emit,toast]);
  const agendaSeed=useRef(false);
  useEffect(()=>{if(!rtc.canHost||!rtc.agendaReady||agendaSeed.current)return;agendaSeed.current=true;if(rtc.agendaItems.length)return;try{JSON.parse(sessionStorage.getItem('etherx_agenda:'+roomCode)||'[]').forEach(topic=>rtc.addAgendaItem(topic.title));}catch{}},[rtc.canHost,rtc.agendaReady,rtc.agendaItems,rtc.addAgendaItem,roomCode]);
  const toggleFs=async()=>{try{if(document.fullscreenElement)await document.exitFullscreen();else await document.documentElement.requestFullscreen();}catch{toast('Full screen is unavailable in this browser.');}};
  const sendChat=async()=>{const text=s.draft.trim();if(!text)return;try{await apiClient.post(`/api/rooms/chat/${roomCode}`,{message:text});patch({draft:''});}catch(e){toast(e.response?.data?.message||'Message not sent. Your draft stays here.');}};
  const sendFb=async()=>{if(!s.rating)return toast('Choose a rating first.');try{await apiClient.post('/api/feedback',{rating:s.rating,text:s.fbText,roomCode});patch({fbSent:true});}catch(e){toast(e.response?.data?.message||'Feedback was not sent. Try again.');}};
  const sendInvite=async()=>{const email=s.inviteEmail.trim();if(!/^\S+@\S+\.\S+$/.test(email))return toast('Enter a valid email address.');try{const res=await apiClient.post(`/api/rooms/${roomCode}/invitations`,{email});if(res.data.mode==='draft'){const anchor=document.createElement('a');anchor.href=res.data.mailto;anchor.click();toast('Email draft opened. Send it from your mail app.');}patch(prev=>({invited:[...prev.invited,{e:email,status:res.data.mode==='draft'?'Draft opened':'Invite sent'}],inviteEmail:''}));}catch(e){toast(e.response?.data?.message||'Invitation could not be sent.');}};

  const startMedia=()=>{let url;try{url=new URL(s.mediaUrl.trim());if(!['http:','https:'].includes(url.protocol))throw new Error();}catch{return patch({mediaErr:'Enter a full link starting with http:// or https://'});}
    if(youtubeId(url.href)){rtc.shareMedia(url.href,'youtube');return patch({modal:null,mediaErr:'',spot:null});}
    // Video sites serve web pages, not playable files.
    if(/(^|\.)(youtube\.com|youtu\.be|vimeo\.com|instagram\.com|tiktok\.com|facebook\.com|drive\.google\.com)$/i.test(url.hostname))return patch({mediaErr:"That site can't be played here. YouTube links work; for other sites use a direct .mp4/.webm/.mp3 link, or Share screen."});
    try{rtc.shareMedia(url.href,s.mediaKind);patch({modal:null,mediaErr:'',spot:null});}catch{patch({mediaErr:'Enter a full link starting with http:// or https://'});}};
  const onFiles=async event=>{const files=[...(event.target.files||[])];event.target.value='';for(const file of files){if(file.size>10*1024*1024){toast('Files must be under 10 MB.');continue;}try{await rtc.shareFile(file);}catch(e){toast(e.response?.data?.message||`${file.name} could not be uploaded.`);}}};
  const changePreference=(key,value)=>{patch({[key]:value});if(key==='mirror')return;const next={...preferences,reference:{...preferences.reference,[key]:value}};savePreferences(next);};
  const chooseDevice=async(kind,id)=>{try{await rtc.switchDevice(kind,id);savePreferences({...preferences,devices:{...preferences.devices,[kind]:id}});}catch(e){toast('Could not switch device: '+e.message);}};
  const toggleNoise=()=>rtc.toggleNoiseSuppression();
  const toggleRecording=()=>rec.isRecording?rec.stopRecording():rec.startRecording();
  const toggleHand=()=>rtc.handQueue.some(h=>h.socketId===rtc.mySocketId)?rtc.sendHandLower():rtc.sendHandRaise();
  const toggleCaptions=()=>patch({captions:!s.captions});
  const notesText=()=>`EtherX Meet · ${roomCode}\nDuration: ${fmt(s.secs)}\nParticipants: ${s.roster.length||Object.keys(rtc.peers).length+1}\n\nAgenda\n${rtc.agendaItems.map(a=>`[${a.done?'x':' '}] ${a.title}`).join('\n')||'None'}\n\nPolls\n${rtc.polls.map(p=>p.question+'\n'+p.options.map(o=>'  '+o.text+': '+o.voters.length).join('\n')).join('\n')||'None'}\n\nNotes\n${s.notes}`;
  const downloadNotes=()=>{const url=URL.createObjectURL(new Blob([notesText()],{type:'text/plain'}));const anchor=document.createElement('a');anchor.href=url;anchor.download='etherx-meeting-notes.txt';anchor.click();setTimeout(()=>URL.revokeObjectURL(url),1000);};
  const endForAll=async()=>{try{await rec.stopRecording();rtc.updateNotes(s.notes);localStorage.setItem('etherx_meeting_notes:'+roomCode,JSON.stringify({notes:s.notes,summary:notesText()}));await emit('end-meeting',{notes:s.notes});}catch(e){toast(e.message);}};
  const me=s.name.trim()||'Guest',canMod=rtc.canHost,amHost=rtc.amHost,micLive=!rtc.micMuted,camLive=!rtc.cameraOff&&!!rtc.localStream;
  const myAvatar=s.roster.find(p=>p.socketId===rtc.mySocketId)?.avatar||getStoredUser()?.avatar||null;
  const roster=s.roster.length?s.roster:[{socketId:rtc.mySocketId,userName:me,isHost:amHost},...Object.entries(rtc.peers).map(([id,p])=>({...p,socketId:id}))];
  const persons=[{id:'me',me:true,name:me,avatar:myAvatar,muted:!micLive,stream:effects?processed:rtc.localStream},...Object.entries(rtc.peers).map(([id,p])=>({id,name:roster.find(r=>r.socketId===id)?.userName||p.userName||'Guest',avatar:roster.find(r=>r.socketId===id)?.avatar||p.avatar||null,muted:!!p.isMuted,camOff:!!p.videoOff,stream:p.stream,screenStream:p.screenStream}))];
  // Camera-off tiles take a darker shade of the person's profile photo colour; people without a photo get a colour from their name.
  const avatarKey=persons.map(p=>p.avatar||'').join('\n');
  useEffect(()=>{let alive=true;for(const src of new Set(avatarKey.split('\n').filter(Boolean)))avatarColor(src).then(rgb=>{if(alive&&rgb)setPhotoTones(prev=>prev[src]?prev:{...prev,[src]:rgb});});return()=>{alive=false;};},[avatarKey]);
  const tileTone=p=>photoTones[p.avatar]?tileShade(photoTones[p.avatar]):tone(p.name)[0];
  const roleOf=p=>p.me?(amHost?'Host':rtc.isCoHost?'Co-host':''):rtc.coHost?.socketId===p.id?'Co-host':roster.find(r=>r.socketId===p.id)?.isHost?'Host':'';
  const hands=rtc.handQueue.map((h,i)=>({id:h.socketId===rtc.mySocketId?'me':h.socketId,name:h.socketId===rtc.mySocketId?me+' (you)':h.userName,num:i+1}));const handPos=id=>hands.findIndex(h=>h.id===id)+1;
  let items=persons.filter(p=>!(p.me&&s.selfHidden&&persons.length>1));
  const media=rtc.sharedMediaUrl,main=media?'media':rtc.isScreenSharing?'screen':rtc.screenSharerId?'remote-screen':s.spot||(!s.grid?(items.some(p=>p.id===s.speaker)?s.speaker:'me'):null);
  if(rtc.screenSharerId){const sharer=items.find(p=>p.id===rtc.screenSharerId);/* the screen arrives on its own video line, so the presenter's tile keeps their camera */if(sharer)items=[{id:'remote-screen',kind:'screen',stream:sharer.screenStream||sharer.stream},...(sharer.screenStream?items:items.map(p=>p.id===sharer.id?{...p,stream:null,camOff:true}:p))];}
  if(main==='screen')items=[{id:'screen',kind:'screen',stream:rtc.screenStream},...items];else if(main==='media')items=[{id:'media',kind:'media'},...items];else if(main||s.pinSpeaker){const focus=main||s.speaker;items=[...items.filter(p=>p.id===focus),...items.filter(p=>p.id!==focus)];}
  const stage=!!main&&items.length>1,stackStage=stage&&narrow&&(s.height||innerHeight)>(s.width||innerWidth),stripCols=items.length-1<=2?1:items.length-1<=6?2:3,cols=narrow?(items.length<=2&&(s.height||innerHeight)>(s.width||innerWidth)?1:Math.min(2,items.length)):items.length<=1?1:items.length<=4?2:items.length<=9?3:4;
  const backgroundOptions=/^data:image\/|^https?:\/\//i.test(s.bg||'')?[...BGS,{id:s.bg,label:'Custom',css:`url("${s.bg}") center / cover`}]:BGS;
  const bg=backgroundOptions.find(b=>b.id===s.bg)||BGS[0],filter=FILTERS.find(f=>f.id===s.filter)||FILTERS[0];
  const camLiveOf=p=>!!p.stream?.getVideoTracks().some(t=>t.readyState==='live')&&!(p.me?rtc.cameraOff:p.camOff);
  const tiles=items.map((p,i)=>({key:p.id,col:stackStage?(i===0||(stripCols===2&&i===items.length-1&&(items.length-1)%2===1)?'1 / -1':'auto'):stage?(i===0?'1':'2'):'auto',row:stackStage?(i===0?'1':'auto'):stage&&i===0?'1 / -1':'auto',radius:s.rounded?'16px':'4px',isPerson:!p.kind,isScreen:p.kind==='screen',isMedia:p.kind==='media',bg:p.kind?'var(--c-050504)':!camLiveOf(p)?tileTone(p):p.me?bg.css:'var(--c-15130f)',avatarBg:tone(p.name)[1],ring:s.spot===p.id?'var(--c-6b5a24)':'transparent',glow:'none',freeze:rtc.networkQuality==='poor'&&!p.me?'grayscale(.7) brightness(.7)':'none',initials:ini(p.name),avatar:p.avatar,name:p.name+(p.me?' (you)':''),muted:p.muted,stream:p.stream,showVid:camLiveOf(p),showAv:!camLiveOf(p),hand:handPos(p.id)>0,handLabel:'Hand '+handPos(p.id),badge:roleOf(p),hasBadge:!!roleOf(p),meter:!p.muted,bars:['3px','3px','3px'],vfilter:'none',vflip:p.me&&s.mirror?'scaleX(-1)':'none',showName:s.showNames,screenLabel:p.id==='screen'?'Your screen':(roster.find(r=>r.socketId===rtc.screenSharerId)?.userName||'Participant')+"’s screen",screenTitle:p.id==='screen'?"You're presenting your screen":'Waiting for the presenter',screenFallbackNote:p.id==='screen'?"Screen preview isn't available in this window":'The shared screen will appear here.',screenFallback:!p.stream,isVideoMedia:rtc.sharedMediaKind==='video',isYouTube:rtc.sharedMediaKind==='youtube',isAudioMedia:rtc.sharedMediaKind==='audio',click:()=>!p.kind&&patch({spot:s.spot===p.id?null:p.id}),onSpeaking}));
  const tileRects=useRef(new Map()),tileOrder=tiles.map(t=>t.key).join('|');
  // Motion, as in the design: tiles enter and FLIP to new positions/sizes, toasts drop in, menus, dialogs and panels pop in.
  // Runs after every render; each element animates once per change. Skipped entirely for reduced motion.
  useLayoutEffect(()=>{const root=rootRef.current;if(!root||!root.animate||window.matchMedia?.('(prefers-reduced-motion: reduce)').matches){tileRects.current=new Map();return;}
    const ease='cubic-bezier(0.2, 0.8, 0.2, 1)',previous=tileRects.current,next=new Map(),first=!previous.size&&!tileRects.seeded;
    root.querySelectorAll('[data-tile]').forEach(el=>{const r={left:el.offsetLeft,top:el.offsetTop,width:el.offsetWidth,height:el.offsetHeight},p=previous.get(el.dataset.tile);next.set(el.dataset.tile,r);
      if(first||!r.width||!r.height)return;
      // Never restart a running enter/move animation: restarting mid-flight is what makes layouts jitter.
      if(el.getAnimations().some(a=>a.playState==='running'&&!(window.CSSTransition&&a instanceof CSSTransition)))return;
      if(!p){el.animate([{opacity:0,transform:'scale(0.86)'},{opacity:1,transform:'none'}],{duration:460,easing:ease,delay:60,fill:'backwards'});return;}
      if(Math.abs(p.left-r.left)>1||Math.abs(p.top-r.top)>1||Math.abs(p.width-r.width)>1||Math.abs(p.height-r.height)>1){const sx=p.width/r.width,sy=p.height/r.height;
        el.animate([{transformOrigin:'0 0',transform:`translate(${p.left-r.left}px,${p.top-r.top}px) scale(${sx},${sy})`},{transformOrigin:'0 0',transform:'none'}],{duration:520,easing:ease});
        // Counter-scale the contents so video and names never look stretched while the tile resizes.
        el.querySelectorAll(':scope > *').forEach(c=>c.animate([{transform:`scale(${1/sx},${1/sy})`},{transform:'none'}],{duration:520,easing:ease}));}});
    tileRects.current=next;tileRects.seeded=true;
    root.querySelectorAll('[data-toast]').forEach(el=>{if(el.dataset.in===el.dataset.toast)return;el.dataset.in=el.dataset.toast;el.animate([{opacity:0,transform:'translateY(-8px) scale(0.96)'},{opacity:1,transform:'none'}],{duration:300,easing:ease});});
    root.querySelectorAll('[data-pop]').forEach(el=>{if(el.dataset.popped)return;el.dataset.popped='1';const k=el.dataset.pop,from=k==='panel'?(narrow?'translateY(32px)':'translateX(28px)'):k==='menu'?'translateY(8px) scale(0.97)':'translateY(10px) scale(0.97)';
      el.animate([{opacity:0,transform:from},{opacity:1,transform:'none'}],{duration:k==='panel'?300:200,easing:ease});});
  });
  // Reactions float up from the reaction layer, like the design. Names come from other users: text only, never HTML.
  const seenReactions=useRef(new Set());
  useEffect(()=>{const host=rxRef.current;rtc.reactions.forEach(r=>{if(seenReactions.current.has(r.id))return;seenReactions.current.add(r.id);if(!host)return;
    const el=document.createElement('div');el.style.cssText=`position:absolute;bottom:0;left:${Math.random()*70}%;display:flex;flex-direction:column;align-items:center;gap:4px;pointer-events:none`;
    const emoji=document.createElement('span');emoji.style.cssText='font-size:40px;line-height:1';emoji.textContent=r.emoji;
    const who=document.createElement('span');who.style.cssText="font:600 11px 'Instrument Sans',sans-serif;color:var(--t-1a1608);background:var(--c-d9b54a);padding:2px 7px;border-radius:6px;white-space:nowrap";who.textContent=r.socketId==='local'?'You':(r.userName||'Guest');
    el.append(emoji,who);host.appendChild(el);
    if(!el.animate||window.matchMedia?.('(prefers-reduced-motion: reduce)').matches){setTimeout(()=>el.remove(),2000);return;}
    const dx=(Math.random()-0.5)*60;el.animate([{transform:'translate(0,0) scale(0.5)',opacity:0},{transform:'translate(0,-40px) scale(1.15)',opacity:1,offset:0.12},{transform:`translate(${dx}px,-340px) scale(1)`,opacity:0}],{duration:2800,easing:'cubic-bezier(0.2,0.6,0.3,1)',fill:'forwards'}).onfinish=()=>el.remove();});
  },[rtc.reactions]);
  // Arriving from the lobby: fade the room in instead of snapping.
  useEffect(()=>{if(!document.body.animate||window.matchMedia?.('(prefers-reduced-motion: reduce)').matches)return undefined;const veil=document.createElement('div');veil.style.cssText='position:fixed;inset:0;background:var(--c-0b0a08);z-index:100;pointer-events:none';document.body.appendChild(veil);const fade=veil.animate([{opacity:1},{opacity:0}],{duration:450,easing:'ease-out',fill:'forwards'});fade.onfinish=()=>veil.remove();return()=>veil.remove();},[]);
  const idle={bg:'transparent',fg:'var(--t-e8e2d3)'},active={bg:'var(--c-2a2414)',fg:'var(--t-ecd389)'},off={bg:'var(--c-d8443d)',fg:'white'},on={bg:'var(--c-1d1a14)',fg:'var(--t-f3eee2)'};
  const b={mic:micLive?on:off,cam:camLive?on:off,share:rtc.isScreenSharing?active:idle,react:s.menu==='react'?active:idle,chat:s.panel==='chat'?active:idle,hand:handPos('me')?active:idle,people:s.panel==='people'?active:idle,more:s.menu==='more'?active:idle};
  const qt=(label,d,run,state)=>({label,d,...(state==='rec'?{bg:'var(--c-3a1716)',fg:'var(--t-ff8a83)',border:'var(--c-5a2420)'}:state?{bg:'var(--c-2a2414)',fg:'var(--t-ecd389)',border:'var(--c-6b5a24)'}:{bg:'var(--c-16140f)',fg:'var(--t-e8e2d3)',border:'var(--c-26231c)'}),run:()=>{patch({menu:null});run();}});
  const mi=(label,d,run,extra='')=>({label,d,extra,hasExtra:!!extra,run:()=>{patch({menu:null});run();}});
  const tg=(label,desc,key,scope='local')=>{const value=scope==='theme'?resolvedTheme==='light':scope==='policy'?s.policy[key]:scope==='room'?rtc.roomLocked:!!s[key];return{label,desc,track:value?'var(--c-d9b54a)':'var(--c-2e2a21)',knob:value?'18px':'2px',flip:()=>scope==='theme'?setTheme(value?'dark':'light'):scope==='policy'?command('meeting-policy-set',{[key]:!value}):scope==='room'?rtc.setRoomLocked(!value):changePreference(key,!value)};};
  const dev=(list,kind,current)=>[{deviceId:kind==='video'?'':'default',label:'System default'},...list.filter(d=>d.deviceId!=='default')].map((d,i)=>({label:d.label||`${kind==='video'?'Camera':kind==='audio'?'Microphone':'Speaker'} ${i+1}`,check:(current|| (kind==='video'?'':'default'))===d.deviceId?'var(--t-d9b54a)':'transparent',pick:()=>{if(kind==='speaker'){savePreferences({...preferences,outputDevice:d.deviceId});patch({menu:null});}else chooseDevice(kind,d.deviceId);}}));
  const quickTiles=[canMod&&qt(rec.isRecording?'Stop recording':'Record',IC.rec,toggleRecording,rec.isRecording?'rec':false),qt(s.grid?'Speaker view':'Grid view',IC.video,()=>patch({grid:!s.grid,spot:null})),qt(s.captions?'Captions on':'Captions',IC.cc,toggleCaptions,s.captions),qt('Whiteboard',IC.wb,()=>patch({wb:true})),qt('Invite people',IC.invite,()=>openModal('invite')),qt(s.fs?'Exit full screen':'Full screen',IC.full,toggleFs,s.fs),...(narrow?[qt(rtc.isScreenSharing?'Stop sharing':'Share screen',IC.share,rtc.toggleScreenShare,rtc.isScreenSharing),qt(handPos('me')?'Lower hand':'Raise hand',IC.hand,toggleHand,handPos('me')),qt('Participants',IC.people,()=>openPanel('people'),s.panel==='people'),qt('Chat',IC.chat,()=>openPanel('chat'),s.panel==='chat')]:[])].filter(Boolean);
  const moreSections=[{title:'MEETING TOOLS',items:[mi('Agenda',IC.agenda,()=>openPanel('agenda')),mi('Polls',IC.poll,()=>openPanel('polls'),rtc.polls.some(p=>p.active)?'Live':''),mi('File sharing',IC.file,()=>openPanel('files'),rtc.sharedFiles.length?String(rtc.sharedFiles.length):''),canMod&&mi('Security options',IC.shield,()=>openModal('security'),rtc.roomLocked?'Locked':''),canMod&&mi('Breakout rooms',IC.grid,()=>openModal('breakout'),s.breakout?'Open':''),canMod&&mi('Share video',IC.video,()=>openModal('media',{mediaKind:'video',mediaErr:''})),canMod&&mi('Share audio',IC.audio,()=>openModal('media',{mediaKind:'audio',mediaErr:''}))].filter(Boolean)},
    {title:'AUDIO AND VIDEO',items:[mi('Noise suppression',IC.noise,toggleNoise,rtc.noiseSuppressed?'On':'Off'),mi('Background',IC.bg,()=>openModal('settings',{tab:'Backgrounds'})),mi('Performance',IC.perf,()=>openModal('performance')),mi('Participant stats',IC.stats,()=>patch({panel:'people',allStats:true}))]},
    {title:'MORE',items:[mi('Settings',IC.settings,()=>openModal('settings')),mi('Shortcuts',IC.keys,()=>openModal('settings',{tab:'Shortcuts'})),mi('Leave feedback',IC.feedback,()=>openModal('feedback',{fbSent:false}))]}].filter(Boolean);
  const otherMembers=roster.filter(p=>p.socketId!==rtc.mySocketId),order=otherMembers.map((p,i)=>({p,k:Math.sin((i+1)*9301+s.brSeed*49297)})).sort((a,b)=>a.k-b.k).map(o=>o.p);
  const brRooms=s.breakout?s.breakout.rooms:Array.from({length:s.brCount},(_,i)=>({id:'breakout-'+(i+1),name:'Room '+(i+1),members:order.filter((_,j)=>j%s.brCount===i).map(p=>p.socketId)}));
  const covered=rtc.agendaItems.filter(a=>a.done).length,kn=rtc.joinRequests[0];
  const tabSelects=(s.tab==='Audio'?[['Microphone',rtc.devices.microphones,'audio',rtc.selectedDevices.audio],['Speaker',rtc.devices.speakers,'speaker',preferences.outputDevice]]:s.tab==='Video'?[['Camera',rtc.devices.cameras,'video',rtc.selectedDevices.video]]:[]).map(([label,list,kind,current])=>({label,value:current|| (kind==='video'?'':'default'),options:[{label:'System default',value:kind==='video'?'':'default'},...list.filter(d=>d.deviceId!=='default').map((d,i)=>({label:d.label||label+' '+(i+1),value:d.deviceId}))],onChange:e=>kind==='speaker'?savePreferences({...preferences,outputDevice:e.target.value}):chooseDevice(kind,e.target.value)}));
  const v={
    rootRef,dialogRef,roomCode,roomTitle:roomCode.replace(/-/g,' ').replace(/\b\w/g,c=>c.toUpperCase()),lobbyUrl:'/',whiteboard:s.wb?<Whiteboard socket={rtc.socket} roomCode={roomCode} isOpen isHost={canMod} canDraw={canMod||!!s.policy.allowDrawing} socketReady={rtc.socketReady} onClose={()=>patch({wb:false})}/>:null,
    headerPadR:s.panel&&!narrow?'392px':'20px',stagePadR:s.panel&&!narrow?'388px':'16px',roomy:!narrow,stackStage,pip:narrow&&items.length===2&&!items.some(p=>p.kind)&&!s.spot,pTop:narrow?'112px':'64px',pLeft:narrow?'12px':'auto',pW:narrow?'auto':'360px',reactLeft:narrow?'0px':'170px',moreRight:narrow?'0px':'70px',chromeOp:s.idle&&!s.menu&&!s.panel&&!s.modal?0:1,footY:s.idle&&!s.menu&&!s.panel&&!s.modal?'translateY(14px)':'none',
    hostMuted:rtc.hostMuted,reconnecting:!rtc.socketReady||rtc.networkQuality==='poor',showConsent:rec.isRecording&&!s.recAck,ackRec:()=>patch({recAck:true}),mutedHint:!!s.mutedHint&&!micLive,unmuteNow:rtc.toggleMic,
    previews:[...(s.chatNotif?s.previews:[]).map(p=>({...p,open:()=>openPanel('chat')})),...(s.panel==='polls'?[]:rtc.pollNotifications.map(p=>({id:'poll-'+p.id,who:p.createdBy+' started a poll',text:p.question,initials:ini(p.createdBy),open:()=>{rtc.dismissPollNotification(p.id);patch({panel:'polls',menu:null});}}))),...(s.panel==='agenda'?[]:s.agendaPops.map(p=>({...p,open:()=>patch(prev=>({panel:'agenda',menu:null,agendaPops:prev.agendaPops.filter(x=>x.id!==p.id)}))}))),...(s.panel==='files'?[]:rtc.fileNotifications.filter(f=>f.sharedBySocketId!==rtc.mySocketId).map(f=>({id:'file-'+f.id,who:f.sharedBy+' shared a file',text:f.name,initials:ini(f.sharedBy),open:()=>{rtc.dismissFileNotification(f.id);patch({panel:'files',menu:null});}})))].slice(-3),previewRight:s.panel&&!narrow?'388px':'16px',wide:(s.width||innerWidth)-(s.panel?384:0)>=1100,mediaVideoRef,mediaAudioRef,youtubeRef,elapsed:fmt(s.secs),recording:rec.isRecording,recLabel:'REC '+fmt(s.recStarted?Math.floor((Date.now()-s.recStarted)/1000):0),locked:rtc.roomLocked,
    codeLabel:s.copied==='code'?'Copied':roomCode,copyCode:()=>copy(roomCode,'code'),linkShort:s.copied==='link'?'Copied':'Copy',emptyCode:roomCode,codeCopied:s.copied==='code',copyEmptyCode:()=>copy(roomCode,'code'),canShareLink:typeof navigator!=='undefined'&&!!navigator.share,shareLink:()=>navigator.share({title:'Join my EtherX meeting',url:link}).catch(()=>{}),emailInvite:()=>openModal('invite'),emptyHint:canMod&&s.policy.waitingRoom?'Share this link. People who open it wait in the lobby until you admit them.':'Share this link with the people you want to meet.',copyLink:e=>{e?.stopPropagation();copy(link,'link');},netBars:[4,7,10,13].map((h,i)=>({h:h+'px',c:i<(rtc.socketReady?(rtc.networkQuality==='good'?4:rtc.networkQuality==='fair'?3:2):0)?(rtc.networkQuality==='good'?'var(--c-6fcf8f)':rtc.networkQuality==='fair'?'var(--c-d9b54a)':'var(--c-e0605a)'):'var(--c-3a3424)'})),netLabel:!rtc.socketReady?'Connecting…':rtc.networkQuality==='good'?'Excellent':rtc.networkQuality==='fair'?'Good':'Unstable',myAvatar,myInitials:ini(me),myName:me,isHost:amHost,canMod,
    /* phones in portrait: shared screen full width on top, cameras in rows of up to 3 beneath (like Meet) */gridCols:stackStage?`repeat(${stripCols},minmax(0,1fr))`:stage?`minmax(0,1fr) ${narrow?'110px':'240px'}`:`repeat(${cols},minmax(0,1fr))`,gridRows:stackStage?`auto repeat(${Math.ceil((items.length-1)/stripCols)},minmax(110px,1fr))`:stage?`repeat(${Math.max(items.length-1,3)},minmax(0,1fr))`:`repeat(${Math.ceil(items.length/cols)},minmax(0,1fr))`,tiles,screenRef,rxRef,chatListRef,fileRef,mediaSrc:media||'',stopMedia:e=>{e?.stopPropagation();if(canMod)rtc.shareMedia(null);},toasts:s.toasts,
    showKnock:canMod&&!!kn&&s.panel!=='people',knockName:kn?.userName||'',knockMore:rtc.joinRequests.length>1?`and ${rtc.joinRequests.length-1} more want to join`:'wants to join',knockAdmit:()=>kn&&rtc.admitUser(kn.socketId),knockDeny:()=>kn&&rtc.denyUser(kn.socketId),ptt:s.ptt,
    captions:s.captions,capWho:s.capLines.at(-1)?.name? s.capLines.at(-1).name+':':'',capLine:s.capLines.at(-1)?.text||s.capNotice||(s.capMissing?.length?'Not captioned (browser unsupported): '+s.capMissing.join(', '):'Listening…'),capColor:!s.capLines.at(-1)?.text&&(s.capNotice||s.capMissing?.length)?'var(--t-a49c8a)':'var(--c-f3eee2)',b,micLive,micDead:!micLive,camOn:camLive,camOff:!camLive,micTitle:rtc.hostMuted?'Microphone muted by host':micLive?'Mute (M)':'Unmute (M) · hold Space to talk',camTitle:camLive?'Turn camera off (V)':'Turn camera on (V)',toggleMic:rtc.toggleMic,toggleCam:rtc.toggleCamera,
    openMicMenu:()=>menu('mic'),openCamMenu:()=>menu('cam'),openReact:()=>menu('react'),openMore:()=>menu('more'),menuMic:s.menu==='mic',menuCam:s.menu==='cam',menuReact:s.menu==='react',menuMore:s.menu==='more',menuLeave:s.menu==='leave',micList:dev(rtc.devices.microphones,'audio',rtc.selectedDevices.audio),spkList:dev(rtc.devices.speakers,'speaker',preferences.outputDevice),camList:dev(rtc.devices.cameras,'video',rtc.selectedDevices.video),toggleNoise,noiseLabel:rtc.noiseSuppressed?'On':'Off',noiseFg:rtc.noiseSuppressed?'var(--t-d9b54a)':'var(--t-7d7666)',openAudioSettings:()=>openModal('settings',{tab:'Audio'}),openVideoSettings:()=>openModal('settings',{tab:'Video'}),openBgSettings:()=>openModal('settings',{tab:'Backgrounds'}),togglePresent:()=>s.policy.allowShare||canMod?rtc.toggleScreenShare():toast('Screen sharing is limited to hosts.'),emojis:['👍','👏','😂','❤️','🎉','😮'].map(emo=>({emo,send:()=>{rtc.sendReaction(emo);patch({menu:null});}})),openChat:()=>openPanel('chat'),unread:s.unread&&s.chatNotif&&s.panel!=='chat',toggleHand,handTitle:handPos('me')?'Lower hand (H)':'Raise hand (H)',openPeople:()=>openPanel('people'),peopleBadge:canMod&&rtc.joinRequests.length?String(rtc.joinRequests.length):String(roster.length),peopleBadgeBg:canMod&&rtc.joinRequests.length?'var(--c-d9b54a)':'var(--c-2a2519)',peopleBadgeFg:canMod&&rtc.joinRequests.length?'var(--c-1a1608)':'var(--c-d9b54a)',leaveClick:()=>canMod?menu('leave'):leave(),doLeave:()=>leave(),openEnd:()=>openModal('notes',{notes:rtc.sharedNotes||s.notes||rtc.agendaItems.map(a=>'- '+a.title+': ').join('\n')}),quickTiles,moreSections,roleLabel:amHost?'Host':rtc.isCoHost?'Co-host':'Participant',
    panelOpen:!!s.panel,panelTitle:({chat:'Chat',people:'Participants',agenda:'Meeting agenda',polls:'Polls',files:'Files'})[s.panel]||'',closePanel:()=>patch({panel:null,allStats:false}),isChat:s.panel==='chat',isPeople:s.panel==='people',isAgenda:s.panel==='agenda',isPolls:s.panel==='polls',isFiles:s.panel==='files',messages:s.messages.map(m=>({who:m.address,text:m.message,time:new Date(m.timestamp||m.createdAt||Date.now()).toLocaleTimeString(undefined,{hour:'2-digit',minute:'2-digit'}),color:String(m.senderId)===String(getStoredUser()?.id)?'var(--t-d9b54a)':'var(--t-e8e2d3)',initials:ini(m.address)})),chatLocked:!s.policy.allowChat&&!canMod,chatOpen:s.policy.allowChat||canMod,draft:s.draft,onDraft:e=>patch({draft:e.target.value}),onDraftKey:e=>{if(e.key==='Enter'){e.preventDefault();sendChat();}},sendChat,q:s.q,onQ:e=>patch({q:e.target.value}),inCount:'In this meeting · '+roster.length,
    hasHands:hands.length>0,handRows:hands.map(h=>({num:String(h.num),name:h.name,canLower:canMod||h.id==='me',lower:()=>h.id==='me'?rtc.sendHandLower():command('lower-participant-hand',{socketId:h.id})})),hasWaiting:canMod&&rtc.joinRequests.length>0,waitRows:rtc.joinRequests.map(r=>({email:r.email||'',since:'Waiting for admission',name:r.userName,initials:ini(r.userName),admit:()=>rtc.admitUser(r.socketId),deny:()=>rtc.denyUser(r.socketId)})),admitAll:()=>rtc.joinRequests.forEach(r=>rtc.admitUser(r.socketId)),peopleRows:roster.filter(p=>!s.q||p.userName.toLowerCase().includes(s.q.toLowerCase())).map(p=>{const local=p.socketId===rtc.mySocketId,id=local?'me':p.socketId,badge=roleOf({id,me:local}),open=s.allStats||s.openP===id;return{avatar:local?myAvatar:p.avatar,initials:ini(local?me:p.userName),name:local?me+' (you)':p.userName,badge,hasBadge:!!badge,muted:local?!micLive:!!p.selfMuted||!!p.hostMuted,hand:handPos(id)>0,handLabel:'Hand '+handPos(id),open,rowBg:open?'var(--c-1a1712)':'transparent',stats:local?(()=>{const setting=rtc.localStream?.getVideoTracks()[0]?.getSettings()||{};return [['Resolution',setting.width?`${setting.width}×${setting.height}`:'Camera off'],['Frame rate',setting.frameRate?`${Math.round(setting.frameRate)} fps`:'—'],['Microphone',micLive?'On':'Muted']].map(([l,v])=>({l,v}));})():s.stats[id]||[{l:'Connection',v:'Measuring…'}],toggle:()=>patch({openP:s.openP===id?null:id,allStats:false}),chev:open?'rotate(180deg)':'none',canAct:canMod&&!local,canCohost:amHost&&!local,muteLabel:p.hostMuted?'Unmute':'Mute',cohostLabel:rtc.coHost?.socketId===p.socketId?'Remove co-host':'Make co-host',mute:()=>p.hostMuted?rtc.unmuteParticipant(p.socketId):rtc.muteParticipant(p.socketId),cohost:()=>rtc.coHost?.socketId===p.socketId?rtc.removeCoHost():rtc.makeCoHost(p.socketId),remove:()=>rtc.kickParticipant(p.socketId)};}),noMatches:!!s.q&&!roster.some(p=>p.userName.toLowerCase().includes(s.q.toLowerCase())),
    agendaProgress:`${covered} of ${rtc.agendaItems.length} covered`,agendaRows:rtc.agendaItems.map(a=>({text:a.title,box:a.done?'var(--c-d9b54a)':'transparent',boxBorder:a.done?'var(--c-d9b54a)':'var(--c-4a4230)',tick:a.done?'var(--c-1a1608)':'transparent',fg:a.done?'var(--t-7d7666)':'var(--t-e8e2d3)',deco:a.done?'line-through':'none',toggle:()=>canMod&&rtc.toggleAgendaItem(a.id),remove:()=>canMod&&rtc.deleteAgendaItem(a.id)})),agendaDraft:s.agendaDraft,onAgendaDraft:e=>patch({agendaDraft:e.target.value}),onAgendaKey:e=>{if(e.key==='Enter'&&canMod&&s.agendaDraft.trim()){rtc.addAgendaItem(s.agendaDraft.trim());patch({agendaDraft:''});}},addAgenda:()=>{if(canMod&&s.agendaDraft.trim()){rtc.addAgendaItem(s.agendaDraft.trim());patch({agendaDraft:''});}},pollQ:s.pollQ,onPollQ:e=>patch({pollQ:e.target.value}),pollOptInputs:s.pollOpts.map((value,i)=>({value,ph:'Option '+(i+1),onChange:e=>patch({pollOpts:s.pollOpts.map((v,j)=>i===j?e.target.value:v)})})),canAddOpt:s.pollOpts.length<5,addOpt:()=>patch({pollOpts:[...s.pollOpts,'']}),launchPoll:()=>{const options=s.pollOpts.map(o=>o.trim()).filter(Boolean);if(!s.pollQ.trim()||options.length<2)return toast('Enter a question and at least two options.');rtc.createPoll(s.pollQ.trim(),options);patch({pollQ:'',pollOpts:['','']});},hasPolls:rtc.polls.length>0,polls:rtc.polls.map(p=>{const total=p.options.reduce((n,o)=>n+o.voters.length,0);return{q:p.question,status:p.active?'Live':'Ended',statusFg:p.active?'var(--t-6fcf8f)':'var(--t-a49c8a)',total:`${total} vote${total===1?'':'s'}`,canEnd:(canMod||p.createdById===rtc.mySocketId)&&p.active,end:()=>rtc.endPoll(p.id),opts:p.options.map((o,i)=>({t:o.text,pct:(total?Math.round(o.voters.length/total*100):0)+'%',w:(total?Math.round(o.voters.length/total*100):0)+'%',border:o.voters.includes(rtc.mySocketId)?'var(--c-6b5a24)':'var(--c-26231c)',bar:o.voters.includes(rtc.mySocketId)?'rgba(217,181,74,.24)':'color-mix(in srgb, var(--c-ffffff) 5%, transparent)',disabled:!p.active,vote:()=>p.active&&rtc.votePoll(p.id,i)}))};}),pickFiles:()=>fileRef.current?.click(),onFiles,hasFiles:rtc.sharedFiles.length>0,files:rtc.sharedFiles.map(f=>({...f,by:f.sharedBy||'',size:typeof f.size==='number'?(f.size>1048576?(f.size/1048576).toFixed(1)+' MB':Math.max(1,Math.round(f.size/1024))+' KB'):f.size,url:`/api/rooms/${roomCode}/files/${f.id}`,download:e=>{e.preventDefault();rtc.downloadFile(f).catch(err=>toast(err.response?.status===404?'This file is no longer shared.':'Download failed. Try again.'));},remove:()=>canMod&&command('remove-shared-file',{id:f.id})})),
    modalOpen:!!s.modal,modalTitle:({settings:'Settings',security:'Security options',performance:'Performance settings',invite:'Invite people',media:'Share media',feedback:'Leave feedback',notes:'Meeting notes',breakout:'Breakout rooms'})[s.modal],closeModal,stop:e=>e.stopPropagation(),isSettings:s.modal==='settings',isInvite:s.modal==='invite',isToggles:s.modal==='security'||s.modal==='performance',isMedia:s.modal==='media',isFeedback:s.modal==='feedback',isNotes:s.modal==='notes',tabs:TABS.map(label=>({label,bg:s.tab===label?'var(--c-24201a)':'transparent',fg:s.tab===label?'var(--t-f3eee2)':'var(--t-a49c8a)',pick:()=>patch({tab:label})})),tab:s.tab,tabSelects,
    tabToggles:({Audio:[{label:'Noise suppression',desc:'Filters keyboard clicks, fans and background chatter',track:rtc.noiseSuppressed?'var(--c-d9b54a)':'var(--c-2e2a21)',knob:rtc.noiseSuppressed?'18px':'2px',flip:toggleNoise}],Video:[tg('Mirror my video','Only changes how you see yourself','mirror'),tg('Send HD video','Turn off on slow connections','hd')],Notifications:[tg('Notification sounds','Play a chime when people join or leave, send a message, raise a hand, share or ask to join','soundCues'),tg('Join and leave alerts','Show a notice when people enter or leave','sounds'),tg('Chat alerts','Show a dot when a new message arrives','chatNotif'),tg('Raised hand alerts','Show a notice when someone raises their hand','handNotif')],Appearance:[tg('Light theme','Switch EtherX Meet between light and dark','theme','theme'),tg('Show names on tiles','Display name labels on every video tile','showNames'),tg('Rounded tiles','Use rounded corners for video tiles','rounded'),tg('Pin active speaker','Move whoever is talking to the first tile in grid view','pinSpeaker')]})[s.tab]||[],isBgTab:s.tab==='Backgrounds',isProfile:s.tab==='Profile',isShortcuts:s.tab==='Shortcuts',bgOptions:backgroundOptions.map(o=>({label:o.label,css:o.css,ring:s.bg===o.id?'var(--c-d9b54a)':'var(--c-2e2a21)',pick:()=>changePreference('bg',o.id)})),filterOptions:FILTERS.map(o=>({label:o.label,css:o.css,ring:s.filter===o.id?'var(--c-d9b54a)':'var(--c-2e2a21)',pick:()=>changePreference('filter',o.id)})),previewMirror:s.mirror,previewBg:bg.css,previewFilter:effects&&processed?'none':filter.css,previewVid:camLive,previewAv:!camLive,previewRef,name:s.name,onName:e=>{patch({name:e.target.value});},shortcuts:SHORTCUTS.map(([k,d])=>({k,d})),
    mt:s.modal==='security'?{title:'Security options',desc:'Control who can join and what participants can do.',toggles:[tg('Lock room','No one new can join, even from the waiting room','locked','room'),tg('Waiting room','People wait until a host admits them','waitingRoom','policy'),tg('Participants can chat','Turn off to make chat host-only','allowChat','policy'),tg('Participants can share screen','Turn off to limit sharing to hosts','allowShare','policy'),tg('Participants can draw on the whiteboard','Pen, marker, eraser and sticky notes. Clearing and images stay with hosts.','allowDrawing','policy')]}:{title:'Performance settings',desc:'Reduce load on slower devices and connections.',toggles:[tg('Hide self-view','Others still see you. Your own tile is hidden.','selfHidden'),tg('Low bandwidth mode','Receive lower-resolution video from others','lowBw')]},inviteLink:link.replace(/^https?:\/\//,''),inviteCopyLink:()=>copy(link,'link'),inviteCopyCode:()=>copy(roomCode,'code'),inviteLinkLabel:s.copied==='link'?'Copied':'Copy link',inviteCodeLabel:s.copied==='code'?'Copied':'Copy code',inviteEmail:s.inviteEmail,onInviteEmail:e=>patch({inviteEmail:e.target.value}),onInviteKey:e=>{if(e.key==='Enter')sendInvite();},sendInvite,hasInvited:s.invited.length>0,invited:s.invited,
    mediaKindTitle:s.mediaKind==='video'?'Share a video':'Share audio',mediaUrl:s.mediaUrl,onMediaUrl:e=>patch({mediaUrl:e.target.value,mediaErr:''}),onMediaKey:e=>{if(e.key==='Enter')startMedia();},mediaPh:s.mediaKind==='video'?'YouTube link or https://example.com/clip.mp4':'https://example.com/track.mp3',mediaErr:s.mediaErr,hasMediaErr:!!s.mediaErr,startMedia,kindOpts:['video','audio'].map(k=>({label:k==='video'?'Video':'Audio',bg:s.mediaKind===k?'var(--c-24201a)':'transparent',fg:s.mediaKind===k?'var(--t-f3eee2)':'var(--t-8a8373)',pick:()=>patch({mediaKind:k})})),stars:[1,2,3,4,5].map(i=>({label:i+' star'+(i===1?'':'s'),fg:i<=s.rating?'var(--t-d9b54a)':'var(--t-3a3424)',set:()=>patch({rating:i})})),fbText:s.fbText,onFb:e=>patch({fbText:e.target.value}),fbSent:s.fbSent,fbForm:!s.fbSent,sendFb,
    notesSummary:[{l:'Duration',v:fmt(s.secs)},{l:'Participants',v:String(roster.length)},{l:'Agenda',v:`${covered} of ${rtc.agendaItems.length} covered`},{l:'Polls',v:String(rtc.polls.length)},{l:'Recording',v:rec.isRecording?'Will be saved':'Not recorded'}],notes:s.notes,onNotes:e=>{patch({notes:e.target.value});rtc.updateNotes(e.target.value);},downloadNotes,endForAll,
    isBreakout:s.modal==='breakout',brOn:!!s.breakout,brSetup:!s.breakout,brPill:'Breakouts · '+fmt(s.breakout?Math.max(0,Math.floor((s.breakout.endsAt-Date.now())/1000)):0),openBreakout:()=>canMod&&openModal('breakout'),brCounts:[2,3,4].map(i=>({label:String(i),bg:s.brCount===i?'var(--c-24201a)':'transparent',fg:s.brCount===i?'var(--t-f3eee2)':'var(--t-8a8373)',pick:()=>patch({brCount:i})})),brDurations:[5,10,15].map(i=>({label:i+' min',bg:s.brMins===i?'var(--c-24201a)':'transparent',fg:s.brMins===i?'var(--t-f3eee2)':'var(--t-8a8373)',pick:()=>patch({brMins:i})})),brRooms:brRooms.map(r=>({...r,members:r.members.map(id=>roster.find(p=>p.socketId===id)?.userName||'Participant'),empty:!r.members.length})),brNote:s.breakout?'Rooms close automatically. Everyone returns to the main room.':otherMembers.length?'People are split evenly. You stay in the main room and can visit any room.':'Breakout rooms need at least one other participant.',brShuffle:()=>patch({brSeed:s.brSeed+1}),brOpen:async()=>{try{await emit('breakout-open',{groups:brRooms.map(r=>r.members),minutes:s.brMins});patch({modal:null});}catch(e){toast(e.message);}},brClose:async()=>{try{await emit('breakout-close');patch({modal:null});}catch(e){toast(e.message);}},overlay:s.left||s.ended,overlayTitle:s.ended?'Meeting ended for everyone':s.replaced?'You joined from another device':'You left the meeting',overlaySub:s.replaced?'Your account is in this meeting on another tab or device. Rejoin here to move it back.':'Call lasted '+fmt(s.secs),canRejoin:!s.ended,rejoin:()=>patch({left:false,replaced:false,fbSent:false}),wb:!!s.wb,
  };
  const missing=REFERENCE_BINDINGS.filter(key=>!(key in v));if(missing.length)throw new Error('Unwired reference controls: '+missing.join(', '));
  if(!rtc.admitted&&!s.left&&!s.ended)return <div className="exmeet-reference" style={{display:'grid',placeItems:'center'}}><section style={{textAlign:'center',maxWidth:400,padding:24}}><h2>{rtc.denied?'Join request declined':rtc.lockedOut?'Meeting is locked':rtc.roomFull?'Meeting is full':'Waiting for the host'}</h2><p>{rtc.connectionError||rtc.mediaError||'Your request is waiting for admission.'}</p><a href="/">Back to home</a></section></div>;
  return <><ReferenceRoomView v={v}/>
    {effects&&rtc.localStream&&!s.left&&!s.ended&&<div style={{position:'fixed',width:2,height:2,opacity:0,pointerEvents:'none'}}><VideoCanvasProcessor stream={rtc.localStream} colorFilter={s.filter} activeFilter={s.bg==='blur'?'half-blur':s.filter} selectedBgImage={bgImage(s.bg)} mirror={false} onOutputStream={processOutput}/></div>}
    {Object.entries(rtc.peers).map(([id,p])=>p.stream&&!s.left&&!s.ended?<RemoteVoice key={id} stream={p.stream} output={preferences.outputDevice}/>:null)}
    {(s.captions||s.captionDemand)&&!s.left&&!s.ended&&<CaptionsOverlay socket={rtc.socket} roomCode={roomCode} show={s.captions} transcribe={(s.captions||s.captionDemand)&&micLive&&!rtc.hostMuted} language={preferences.captionLanguage} onUnavailable={captionUnavailable} render={()=>null} onUpdate={captionUpdate}/>}
    
    {s.breakout&&!s.left&&!s.ended&&<div className="reference-breakout-navigation"><span>{s.breakout.rooms.find(r=>r.id===s.breakout.assignments[rtc.mySocketId])?.name||'Main room'}</span>{canMod&&<>{s.breakout.rooms.map(r=><button key={r.id} onClick={()=>command('breakout-visit',{groupId:r.id})}>Visit {r.name}</button>)}<button onClick={()=>command('breakout-visit',{groupId:'main'})}>Return to main room</button></>}</div>}
  </>;
}
